spring.application.name=pharmacy-management-system
spring.datasource.url=jdbc:mysql://pharmacy-mysql-pharmacy-management-system.a.aivencloud.com:26797/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_YDyTBlofbCPHsvsllhj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true